### ISSUE TITLE
Vencimento do Boleto com base na Fatura

### ISSUE THREAD

**Issue by husanisantos** [widepay/mod-whmcs#1]
Algo que falta no modulo é que a data e inserida do dia que gera a fatura + os dias do campo informado no Admin, e isso é ruim pois se um cliente atrasa e você quer gerar um boleto pra amanhã por exemplo isso só será possível se mudar de todos os clientes, no caso indo até as configurações do modulo e inserindo 1 no campo de **Acréscimo de Dias no Vencimento**.
Seria muito melhor se simplesmente inserisse a data de vencimento do boleto com a mesma data do vencimento da fatura pra não haver confusão e facilitar a vida de quem usa o modulo.

**Comment by gabrielpasches** [comment]
Boa tarde, @husanisantos.
"Seria muito melhor se simplesmente inserisse a data de vencimento do boleto com a mesma data do vencimento da fatura pra não haver confusão e facilitar a vida de quem usa o modulo."
Basta deixar o campo (Acréscimo de Dias no Vencimento):  em branco ou com valor 0

**Comment by husanisantos** [comment]
Boa noite @GabrielPasche , grato pela sua rápida resposta, na verdade eu já havia notado isso por isso havia fechado a questão.
