### ISSUE TITLE
Testando o modulo para whmcs

### ISSUE THREAD

**Issue by vinnyparker** [widepay/mod-whmcs#2]
Olá, estou testando o modulo e ao finalizar uma compra eu encontrei uma mensagem de erro.
O que tentei fazer foi adicionar fundos. gostaria de saber como faço para corrigir os erros, pois ele informa que o campo é obrigatorio, mas nao diz qual.
estou usando whmcs 7.6.0

**Comment by vinnyparker** [comment]
achei que um dos erros era da data, mas continua após correção
![captura de tela em 2018-08-03 16-29-47](https://user-images.githubusercontent.com/1207567/43661979-8a2ffc7e-973a-11e8-9887-a605c1ded10e.png)

**Comment by vinnyparker** [comment]
O campo que era obrigatorio era o cnpj e o cliente nao tinha preenchido. agora no caso do formato da data, eu nao sei o que isso quer dizer, nem como essa validação acontece.

**Comment by claudioalmeiida** [comment]
Qual a versão do seu whmcs @vinnyparker ?

**Comment by vinnyparker** [comment]
estou usando whmcs 7.6.0

**Comment by vinnyparker** [comment]
mas tb ja havia testado na versao 7.5.0 e o erro foi o mesmo

**Comment by gabrielpasches** [comment]
Olá @vinnyparker,
Poderia adicionar essa linha no seu arquivo **modules/gateways/widepay.php** na **linha 287**
`return '<div class="alert alert-danger" role="alert"><pre>' .  var_dump($dados) . '</pre></div>';`

**Comment by gabrielpasches** [comment]
Depois pode mandar um print pra gente do que aconteceu?

**Comment by vinnyparker** [comment]
Bom dia. Aconteceu isso....

![captura de tela em 2018-08-07 09-24-34](https://user-images.githubusercontent.com/1207567/43775622-bcf69578-9a23-11e8-8445-0d0654d42ccd.png)

**Comment by vinnyparker** [comment]
se quiser testar online: financeiro.xhost.net.br. e vai em faturas>> adicionar fundos, ou compra uma das opções q tem la.

**Comment by vinnyparker** [comment]
No Chrome apareceu essa expressao acima "NULL"

![captura de tela em 2018-08-07 09-55-09](https://user-images.githubusercontent.com/1207567/43777022-fef73a00-9a27-11e8-8317-e4bdd87a12e5.png)

**Comment by gabrielpasches** [comment]
Essa cobrança é adicionada na sua conta Wide Pay?

**Comment by vinnyparker** [comment]
correto, vai pra minha conta widepay, apesa do erro de null, seu codigo continua la.

**Comment by gabrielpasches** [comment]
Faz assim, Substitui aquele return que eu passei acima na linha 287 adicionando essas 3 linhas.
```
echo "<pre>";
var_dump($dados);
echo "</pre>";
```

**Comment by gabrielpasches** [comment]
Estou falando isso pq não tenho acesso a nenhuma aplicação whmcs neste momento.

**Comment by vinnyparker** [comment]
tudo bem, feito la

**Comment by gabrielpasches** [comment]
É muito estranho. Não faz sentido ser null e mostrar o erro depois do mesmo objeto.
Coloca:
```
echo "<pre>";
var_dump($dados);
echo "</pre>";
echo "<pre>";
var_dump($widepayData);
echo "</pre>";
```
Assim vai mostrar o que ta mandando pro Wide Pay.

**Comment by vinnyparker** [comment]
um minuto

**Comment by vinnyparker** [comment]
vish
![captura de tela em 2018-08-07 10-29-13](https://user-images.githubusercontent.com/1207567/43778691-c1e48230-9a2c-11e8-869b-98df871a0552.png)

**Comment by gabrielpasches** [comment]
Parece que tem alguma coisa errada com esse var_dump, sempre retorna null.
Pode fazer o teste com o print_r?

```
echo "<pre>";
print_r($dados);
echo "</pre>";
echo "<pre>";
print_r($widepayData);
echo "</pre>";
```

**Comment by vinnyparker** [comment]
Tlvz a variavel ano esteja sendo alimentada, sei la, eu tb tentei imprimir os dados, porem nao tras nada

![captura de tela em 2018-08-07 10-36-47](https://user-images.githubusercontent.com/1207567/43779082-ce88cd6a-9a2d-11e8-9429-df35625ca1c1.png)

**Comment by gabrielpasches** [comment]
Pode mandar um print dessa parte do seu código?

**Comment by vinnyparker** [comment]
Seu codigo ta logo a baixo da funcao que eu coloquei para imprimir os dados...
![captura de tela em 2018-08-07 10-38-58](https://user-images.githubusercontent.com/1207567/43779195-27869186-9a2e-11e8-815f-bace205ccc7f.png)

**Comment by vinnyparker** [comment]
Minha funcao imprime 0
![captura de tela em 2018-08-07 10-40-05](https://user-images.githubusercontent.com/1207567/43779240-439abc3a-9a2e-11e8-8ffc-15d9954d7448.png)

**Comment by gabrielpasches** [comment]
Deixe dessa forma:
![image](https://user-images.githubusercontent.com/6035693/43779310-19bb5454-9a26-11e8-90e7-a6101aba7d26.png)

**Comment by vinnyparker** [comment]
nao funcionou, mas estava olhando aqui que temos conteudos diferentes para as linhas anteriores a 287.

**Comment by vinnyparker** [comment]
tlvz eu esteja na função errada.

**Comment by vinnyparker** [comment]
vou restaurar o codigo da classe widepay.php para o original, e postar aqui

**Comment by gabrielpasches** [comment]
Então, tenta achar essa parte no seu código e coloca o trecho nela.
```
echo "<pre>";
var_dump($dados);
echo "</pre>";
echo "<pre>";
var_dump($widepayData);
echo "</pre>";
```

**Comment by vinnyparker** [comment]
Agora sim: 

$dados:
`object(stdClass)#133 (6) {
  ["sucesso"]=>
  bool(false)
  ["erro"]=>
  string(31) "Erro na validação dos campos."
  ["validacao"]=>
  array(1) {
    [0]=>
    array(2) {
      ["id"]=>
      string(10) "vencimento"
      ["erro"]=>
      string(30) "A data informada é inválida."
    }
  }
  ["success"]=>
  bool(false)
  ["error"]=>
  string(31) "Erro na validação dos campos."
  ["errors"]=>
  array(1) {
    [0]=>
    array(2) {
      ["id"]=>
      string(10) "vencimento"
      ["msg"]=>
      string(30) "A data informada é inválida."
    }
  }
}`

**Comment by vinnyparker** [comment]
$weidepaydata

`array(13) {
  ["forma"]=>
  string(6) "Boleto"
  ["referencia"]=>
  int(11)
  ["notificacao"]=>
  string(70) "https://financeiro.xhost.net.br//modules/gateways/callback/widepay.php"
  ["vencimento"]=>
  string(19) "2018-08-03 00:00:00"
  ["cliente"]=>
  string(13) "Cliente Kraft"
  ["email"]=>
  string(22) "clientekraft@gmail.com"
  ["enviar"]=>
  string(6) "E-mail"
  ["pessoa"]=>
  string(7) "Física"
  ["cpf"]=>
  string(11) "01606569589"
  ["cnpj"]=>
  string(0) ""
  ["endereco"]=>
  array(5) {
    ["rua"]=>
    string(3) "rua"
    ["complemento"]=>
    string(9) "pau miudo"
    ["cep"]=>
    string(8) "40310230"
    ["estado"]=>
    string(2) "BA"
    ["cidade"]=>
    string(8) "Salvador"
  }
  ["itens"]=>
  array(1) {
    [0]=>
    array(2) {
      ["descricao"]=>
      string(42) "Xhost Serviços de Hospedagem - Fatura #11"
      ["valor"]=>
      float(1)
    }
  }
  ["boleto"]=>
  array(4) {
    ["gerar"]=>
    string(3) "Nao"
    ["desconto"]=>
    int(0)
    ["multa"]=>
    float(2)
    ["juros"]=>
    float(1)
  }
}`

**Comment by gabrielpasches** [comment]
Beleza. Vou ver agora aqui.

**Comment by vinnyparker** [comment]
blz, fico grato.

**Comment by gabrielpasches** [comment]
Faz um teste substituindo a linha do vencimento por:

```
'vencimento' => new DateTime($invoiceDuedate)->format('Y-m-d'),
```
![image](https://user-images.githubusercontent.com/6035693/43780537-cfc54758-9a28-11e8-8c4e-dbd39e4f2298.png)

**Comment by vinnyparker** [comment]
tem algum erro de sintaxe

**Comment by vinnyparker** [comment]
![captura de tela em 2018-08-07 11-08-26](https://user-images.githubusercontent.com/1207567/43780975-3ce752e6-9a32-11e8-81fe-89ba569e39ec.png)

**Comment by gabrielpasches** [comment]
![image](https://user-images.githubusercontent.com/6035693/43780962-d66aa598-9a29-11e8-9b14-55d6e4efb26f.png)
```
$invoiceDuedateFormated = new DateTime($invoiceDuedate);
$invoiceDuedateFormated = $invoiceDuedateFormated->format('Y-m-d');

```

![image](https://user-images.githubusercontent.com/6035693/43781026-fb5bf99c-9a29-11e8-817e-11dcbd469d7e.png)

```
'vencimento' => $invoiceDuedateFormated,
```

**Comment by vinnyparker** [comment]
vou trocar o valor do invoice...
![captura de tela em 2018-08-07 11-13-41](https://user-images.githubusercontent.com/1207567/43781305-f9f4b388-9a32-11e8-9a47-bff1be0bbcc0.png)

**Comment by vinnyparker** [comment]
só permite pagamento via boleto?

**Comment by vinnyparker** [comment]
bom, coloquei o valor do invoice para  5 reais e agora funcionou, gerou o boleto

**Comment by gabrielpasches** [comment]
Você pode ativar o cartão desta forma:
![image](https://user-images.githubusercontent.com/6035693/43782364-330ba11e-9a2d-11e8-9985-fc41dbb70043.png)
```
'forma' => 'Boleto,Cartão',
```

**Comment by vinnyparker** [comment]
vou testar

**Comment by vinnyparker** [comment]
so mostrou opcao de boleto mesmo... 
![captura de tela em 2018-08-07 11-39-14](https://user-images.githubusercontent.com/1207567/43782804-886fc474-9a36-11e8-8a2e-61d4cf101226.png)

**Comment by gabrielpasches** [comment]
Mas você criou uma nova fatura ou abriu a página de pagamento novamente?

**Comment by vinnyparker** [comment]
nao, eu testei uma existente

**Comment by gabrielpasches** [comment]
Crie uma nova fatura, "Nova compra"

**Comment by vinnyparker** [comment]
Sim, funcionou. 
Fico agradecido pela ajuda.

**Comment by vinnyparker** [comment]
Seria legal se abrisse light in Box como o mercado pago. Fica a sugestão.
